# Generated by Django 4.2.11 on 2024-03-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('fecha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.TextField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
