# Generated by Django 4.2.11 on 2024-03-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('imagen', models.TextField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
